Main menu
Istalantar/SCJ-2021-classic-clownfish pull request #5
Opened 2021-07-14 18:50 UTC by robincunningham2

Main menu
* Main page
* Select already saved puzzle
* Select new puzzles from `jpg` / `png` files

To do:
* Implement ASCII converter
* Resizing ASCII art to make into tiles (stuck with that)
* Actually playing the game

2021-07-14 18:51 UTC, robincunningham2 commented
Also the code is not written efficiently, so that needs to be fixed too

2021-07-14 20:08 UTC, Bluenix2 requested changes
I can probably comment on more than this, but we'll start here

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    while 1:
Can we switch all of these to using `True`?
```suggestion
    while True:
```

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +)
```suggestion
INSIDE_THE_BOX = [
    ' ┌————————————————————————————————————————————————————————————————————————————————————————┐',
    ' │                                                                                        │',
    ' │         ___ _   _ ____ ___ ____  _____    _____ _   _ _____    ____   _____  __        │',
    ' │        |_ _| \\ | / ___|_ _|  _ \\| ____|  |_   _| | | | ____|  | __ ) / _ \\ \\/ /        │',
    ' │         | ||  \\| \\___ \\| || | | |  _|      | | | |_| |  _|    |  _ \\| | | \\  /         │',
    ' │         | || |\\  |___) | || |_| | |___     | | |  _  | |___   | |_) | |_| /  \\         │',
    ' │        |___|_| \\_|____/___|____/|_____|    |_| |_| |_|_____|  |____/ \\___/_/\\_\\        │',
    ' │                                                                                        │',
    ' │                                                                                        │',
    ' └————————————————————————————————————————————————————————————————————————————————————————┘',
]
```

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +term = Terminal()
Move this inside `if __name__ == '__main__':`

2021-07-14 20:08 UTC, Bluenix2 commented on source/game.py
> +            difficulty = 1
```suggestion
        # Clamp difficulty to 1 <= difficult <= 5
        difficulty = max(1, min(difficulty, 5))
```

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +def render_main(term: Terminal, index: int = 0) -> str:
Instead of passing around the Terminal so much, why not just subclass?

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +        pass
I understand that this is in-place so that the program never exits, but I'd rather have the program exit than be unresponsive to the user. Is this kind of a `TODO` part?

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    """
```suggestion
def main(term: Terminal) -> None:
    """Main function taking care of rendering and complete application lifetime"""
```
Self-explanatory

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +        print(render_main(term, index))
Doing it like this may make the screen flash, we should try to do it together if possible. Also I wouldn't necessarily call this the main-menu yet, it's more of a start menu.

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +                sys.exit(0)
Can we switch these to `elif` where applicable, even though it's the same it shows the expected code execution.

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    splitted = [term.center(term.black_on_white(line) if index == 0 else line) for line in INSIDE_THE_BOX.split('\n')]
```suggestion
    splitted = [term.center(term.black_on_white(line) if index == 0 else line) for line in INSIDE_THE_BOX]
```

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    rendered += term.move_y(term.height - 3)
Why do we do this?

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    rendered += '    ' + term.black_on_white('Exit') if index == 1 else '    ' + 'Exit'
```suggestion
    rendered += '    ' + (term.black_on_white('Exit') if index == 1 else 'Exit')
```

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +    return '0' * (length - len(num)) + num
Strings have this built-in (`rjust()`)

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +        return string[:length - 3] + '...'
Can you sure `elif`s here

2021-07-14 20:08 UTC, Bluenix2 commented on source/main.py
> +        print(render_file_explorer(term, current_dir, files, dirs, index))
This leads to flicker

2021-07-14 20:46 UTC, Istalantar commented on source/game.py
> +        """
Just aesthetics, but In the end all our doctstrings should use the same style
```suggestion
        :param image: image path
        :param difficulty: integer ranging from 1 to 5. Defaults to 1.
        """
```

2021-07-14 20:46 UTC, Istalantar commented on source/main.py
> +            dirs.append('    ' + file + '/')
I don't understand the spaces in line 159, 164 and 166. Are they positioning/line identation?

2021-07-16 14:17 UTC, Bluenix2 approved these changes
This should be able to be Rebase merged.

2021-07-16 16:06 UTC, merged